import type { Metadata } from "next";
// import { Nunito } from "next/font/google";
import { Quicksand } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utills";

const quicksand = Quicksand({ 
  // weight: '500',
  style: 'normal',
  subsets: ["latin"]});

export const metadata: Metadata = {
  title: "PaperConverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={cn('min-h-screen font-sans antialiased grainy', quicksand.className)}>{children}</body>
    </html>
  );
}
