import type { Metadata } from "next";
// import { Nunito } from "next/font/google";
import { Mooli } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utills";
import Navbar from "@/components/Navbar";

const mooli = Mooli({ 
  weight: "400",
  style:  "normal",
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Papyrus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={cn(
          "min-h-screen font-sans antialiased grainy",
          mooli.className
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
